import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
// You should use getServerSideProps when:
// - Only if you need to pre-render a page whose data must be fetched at request time
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'

const inter = Inter({ subsets: ['latin'] })
type Data = {
  friend: Record<string, string>
}

export default function Home({friends}:InferGetServerSidePropsType<typeof getServerSideProps>) {
  console.log(friends);
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {friends.map((x:any,i:number)=>(
        
          <p key={i}>{x.name}</p>
        
      ))}
      </main>
    </>
  )
}



export const getServerSideProps: GetServerSideProps = async (ctx) => {
let friends;
try{
  const response = await fetch(process.env.NEXT_PUBLIC_HASURA_PROJECT_ENDPOINT as string,{
    method:'POST',
    headers:{
      'content-type':'application/json',
      'x-hasura-admin-secret': process.env.HASURA_ADMIN_SECRET as string
    },
    body: JSON.stringify({
      query:`query {
        friend {
          name
        }
      }`
    })
    })
    
    const result = await response.json()
    const data:Data = result.data

    friends = data.friend

    console.log(result)
}catch(e){
console.log(e)
}


  return {
    props: { friends }
  }
}
